### ISSUE TITLE
Custom AutoloadMode

### ISSUE THREAD

**Issue by mufasachan** [Shatur/neovim-session-manager#139]
**Describe the problem or limitation you are having**

I would like to load session when my argv is a single directory. Else, no arg or file args, I do not want to load the session.

The current mode cannot implement this behaviour, I can do it myself by defining a `VimEnter` auto command with a defer by disabling the autoload, which is very hacky.
 
**Describe the solution you'd like**

I think my use case is personal and might not interest much people. Although, it would be nice to add another member of the `AutoloaderMode` enumeration called `Custom` and add a `AutoloadModeCustom` in `values`. This function should return a boolean value, like the other functions for other mode and can be defined by the user.

I think I can implement the PR myself if the idea is ok. I would append the enum and update `autoloaders`. Then in the `opts` I would add `nil` as default for the `autoload_custom` function. In `autoload_session`, I would add a warning message if the enum is set to "Custom" but the function is not defined.

**Comment by Shatur** [comment]
My personal preference is to avoid having a lot of customization options and provide an API for it instead. I think disabling autoload and doing something custom via `VimEnter` is the intended way.
I already regret including some of the functionality, it's better to let users configure what they want via autocommand instead of having many confusing option.

**Comment by mufasachan** [comment]
Okay, I get your point. I think it's very wise. I like your plugin, it's very direct. Thanks for your quick answer!
