### ISSUE TITLE
How to use load session in telescope or nui

### ISSUE THREAD

**Issue by hungnguyen1503** [Shatur/neovim-session-manager#60]
Hi, I'd like to document references to set up the sessions popup menu by nui or telescope menu.
Could you support me by showing a sample code of the load session?
Many thanks

**Comment by Shatur** [comment]
Just call `:SessionManager load_session` and it will work.
You just need to install https://github.com/nvim-telescope/telescope-ui-select.nvim or https://github.com/stevearc/dressing.nvim to override `vim.ui.select` interface.

**Comment by hungnguyen1503** [comment]
Oh great, it has worked very well.
Thank you for your support.

**Comment by benbrastmckie** [comment]
> Just call `:SessionManager load_session` and it will work. You just need to install https://github.com/nvim-telescope/telescope-ui-select.nvim or https://github.com/stevearc/dressing.nvim to override `vim.ui.select` interface.

I've gone with `stevearc/dressing` in attempt to load sessions and it seems to work great. However, I'm struggling to run the command `SessionManager load_session` to run from `goolord/alpha-nvim` so that it becomes a dashboard button. Instead I get the error message "No such subcommand: load_session". Works great when I enter the command by hand. Any thoughts would be greatly apprecated.

**Comment by Shatur** [comment]
I don't use this plugin, can't help.
